CREATE TABLE device (
    id      INTEGER PRIMARY KEY NOT NULL,
    owner   INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE users (
    id          INTEGER PRIMARY KEY NOT NULL,
    username    VARCHAR(60) NOT NULL,
    password    VARCHAR(60) NOT NULL
);