services:
  db_test:
    container_name: postgres_container_test
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: signal_db_test
    ports:
      - "3306:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: signal_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    container_name: redis_container
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
